### ISSUE TITLE
add VisualData Extension to pre declared extensions

### ISSUE THREAD

**Issue by WolfgangFahl** [WolfgangFahl/pymediawikidocker#78]
```yaml
- name: VisualData
  wikidata_id: Q124334208
  url: https://www.mediawiki.org/wiki/Extension:VisualData
  extension: VisualData
  purpose: 'VisualData is a full-fledged metadata management framework based on json-schema able to easily record, organize and query collection of data on your wiki.'
  composer: '"composer install --no-dev"'
 
- name: SubpageNavigation
  wikidata_id: Q123244126
  url: https://www.mediawiki.org/wiki/Extension:SubpageNavigation
  extension: SubpageNavigation
  purpose: 'Shows direct children of current page in article header, provides dynamic subpage tree on the sidebar and a special page to browse all pages/subpages of the wiki in different modalities'

```
